blocklist:
  - 1234567890

blocklist-terms:
  - "prod"
  - "production"
  - "live"

no-blocklist-terms-default: true

accounts:
  "{account_id}":
    account-alias: "o11y-lab"
    filters:
      IAMUser:
        - "nuke"
      IAMGroup:
        - "admin"
      IAMUserGroupAttachment:
        - "nuke -> admin"
      IAMGroupPolicyAttachment:
        - "admin -> AdministratorAccess"
      IAMUserAccessKey:
        - property: UserName
          value: "nuke"

regions:
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - eu-north-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - ap-south-1
  - ap-northeast-1
  - ap-northeast-2
  - ap-northeast-3
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - sa-east-1
  - global
